### ISSUE TITLE
Possible to purge associated URLS for entries that don't have a URL but are listed on associated pages.

### ISSUE THREAD

**Issue by terryupton** [putyourlightson/.github#1]
### Is your feature request related to a problem?
A feature request as I don't believe this is currently possible. 
At the moment you can setup Purge Rules - but this as I understand only purges urls and associated (right side) urls if the source entry has a URL. What I would like is the option to add Purge Rules that purge the associated (right side) urls even if they entry doesn't have a URL.

My use case example is;

I have a section called 'Teams' but these team entries do not have their own URLS. Instead they are all listed via an entry query on a main Teams page. Therefore I would like to purge the main /teams page if any of the Teams entries are updated.

Here is the live example.
https://www.mkunitedfc.co.uk/teams 

Each team card is an entry in a section called Teams.

Thanks
Terry

**Comment by bencroker** [comment]
What plugin are we talking about here? I assume Blitz, but this issue is not in any plugin repo. Please open an issue in the correct repo, adding some detail that explains what you would like to have happen with more clarity.

**Comment by terryupton** [comment]
Sorry Ben. I thought I was on the repo. I was referring to the Cloudflare plugin.
I will re-post on that repo.
